# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # General VM configuration
  config.vm.box = "generic/fedora35"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/home/vagrant/ansible", disabled: false
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # Application server 1
  config.vm.define "App1" do |app|
    app.vm.hostname = "app1.test"
    app.vm.network :private_network, ip: "192.168.60.4"
  end

  # Application server 2
  config.vm.define "App2" do |app|
    app.vm.hostname = "app2.test"
    app.vm.network :private_network, ip: "192.168.60.5"
  end

  # Database server 1
  config.vm.define "db" do |app|
    app.vm.hostname = "db.test"
    app.vm.network :private_network, ip: "192.168.60.6"
  end
end
